"""user table

Revision ID: 2a6509f85d16
Revises:
Create Date: 2025-02-23 16:52:58.116263

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a6509f85d16"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=320), nullable=True),
        sa.Column("password", sa.VARCHAR(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_user")
    # ### end Alembic commands ###
