"""domain event table

Revision ID: ea6a35003ef6
Revises: 2a6509f85d16
Create Date: 2025-04-13 19:57:18.797188

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea6a35003ef6"
down_revision: Union[str, None] = "2a6509f85d16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_event",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("causation_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("aggregate_id", "aggregate_version", name="uq_aggregate_version"),
    )
    op.create_index("domain_event_aggregate_fk", "domain_event", ["aggregate_id"], unique=False)
    op.create_index("domain_event_aggregate_version_idx", "domain_event", ["aggregate_version"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("domain_event_aggregate_version_idx", table_name="domain_event")
    op.drop_index("domain_event_aggregate_fk", table_name="domain_event")
    op.drop_table("domain_event")
    # ### end Alembic commands ###
